# Site settings

title: leewc
email: lee@leewc.com

description: A blog on programming, software development, thoughts, and food.

# Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://legacy.leewc.com" 	# the base hostname & protocol for your site
enforce_ssl: "legacy.leewc.com"

#usernames used in social media links in the contact footer
twitter_username: wenchuanlee
github_username:  leewc
facebook_username: wenchuan21 	#username when you view your timeline (also found in facebook settings)
instagram_username: wenchuan_lee
stackoverflow_username: 4512948/matrixanomaly #userid/username, will be a link as : http://stackoverflow.com/users/{{stackoverflow_username}}

linkedin_profile: https://www.linkedin.com/in/wenchuanlee  #place the link to your linkedin profile here 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: "/:categories/:title" # 'pretty' keeps the dates but removes .html, 'none' does not, but keeps  the .html, this removes dates and the .html

kramdown: 
    input: GFM

excerpt_separator: <!-- more -->

exclude: [_exclude, "README.markdown", "Gemfile.lock", "Gemfile"]

sass:
    sass_dir: assets/css/sass_libs
    #style: compressed #cloudflare is doing this automatically

gems:
    - jekyll-sitemap
    #- jemoji -- disabled till Jekyll 2.5 is used in Github Pages and Jemoji is updated for Jekyll 2.x.