# Site settings

title: Hello there.
footertitle: Contact Me
email: leewenchuan.lwc@gmail.com

#description: > this means to ignore newlines until "baseurl:"
# Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leewc.github.io" # the base hostname & protocol for your site
twitter_username: wenchuanlee
github_username:  leewc

# Build settings
markdown: kramdown
highlighter: pygments

kramdown: 
    input: 'GFM'

exclude: [_exclude, "README.markdown", "Gemfile.lock", "Gemfile"]

gems:
    - jekyll-sitemap